id: SetTranslatedBasename
name: <__trans phrase="Set Translated Basename">
version: 0.3
description: <__trans phrase="Inputted Japanese is translated by Microsoft Translator, and set to basename.">
author_name: <__trans phrase="Taitetsu">
author_link: http://www.hazama.nu/t2o2/
doc_link: http://www.hazama.nu/t2o2/
l10n_class: SetTranslatedBasename::L10N

system_config_template: setting_system.tmpl
blog_config_template: setting_blog.tmpl
settings:
    system_client_id:
        default:
        scope: system
    system_client_secret:
        default:
        scope: system
    system_lang:
        default: ja
        scope: system
    blog_client_id:
        default:
        scope: blog
    blog_client_secret:
        default:
        scope: blog
    blog_lang:
        default: ja
        scope: blog

callbacks:
    MT::App::CMS::template_param.edit_entry: $SetTranslatedBasename::SetTranslatedBasename::hdlr_template_param_edit_entry

applications:
    cms:
        methods:
            translate_basename:
                code: $SetTranslatedBasename::SetTranslatedBasename::translate_basename
