id: SetTranslatedBasename
name: <__trans phrase="Set Translated Basename">
version: 0.6
description: <__trans phrase="Inputted Japanese is translated by Microsoft Translator, and set to basename.">
author_name: <__trans phrase="Taitetsu">
author_link: http://www.hazama.nu/t2o2/
doc_link: http://www.hazama.nu/t2o2/
l10n_class: SetTranslatedBasename::L10N

system_config_template:
    code: $SetTranslatedBasename::SetTranslatedBasename::config_template
blog_config_template:
    code: $SetTranslatedBasename::SetTranslatedBasename::config_template
settings:
    system_client_id:
        default:
        scope: system
    system_client_secret:
        default:
        scope: system
    system_lang:
        default: ja
        scope: system
    blog_client_id:
        default:
        scope: blog
    blog_client_secret:
        default:
        scope: blog
    blog_lang:
        default: ja
        scope: blog

callbacks:
    MT::App::CMS::template_param.edit_entry: $SetTranslatedBasename::SetTranslatedBasename::hdlr_template_param_edit_entry

applications:
    cms:
        methods:
            translate_basename:
                code: $SetTranslatedBasename::SetTranslatedBasename::translate_basename

set_translated_basename_language_codes:
    ar: Arabic
    bg: Bulgarian
    ca: Catalan
    zh-CHS: Chinese (Simplified)
    zh-CHT: Chinese (Traditional)
    cs: Czech
    da: Danish
    nl: Dutch
    en: English
    et: Estonian
    fa: Persian (Farsi)
    fi: Finnish
    fr: French
    de: German
    el: Greek
    ht: Haitian Creole
    he: Hebrew
    hi: Hindi
    hu: Hungarian
    id: Indonesian
    it: Italian
    ja: Japanese
    ko: Korean
    lv: Latvian
    lt: Lithuanian
    ms: Malay
    mww: Hmong Daw
    no: Norwegian
    pl: Polish
    pt: Portuguese
    ro: Romanian
    ru: Russian
    sk: Slovak
    sl: Slovenian
    es: Spanish
    sv: Swedish
    th: Thai
    tr: Turkish
    uk: Ukrainian
    ur: Urdu
    vi: Vietnamese
